# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de la compra')),
                ('valor', models.PositiveIntegerField(default=0, verbose_name='Valor')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_engine.Plato', verbose_name='Plato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
